SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK AS b
JOIN AUTHOR AS a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES AS s ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY 1 ASC, 3 DESC


