-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY GENDER, MONTH(SALES_DATE), YEAR(SALES_DATE)
ORDER BY 1 ASC, 2 ASC, 3 ASC;
