WITH RECURSIVE hours AS (
    -- 초기값
    SELECT 0 AS h
    -- 
    UNION ALL
    -- 재귀 부분
    SELECT h + 1 
    FROM hours
    -- 기저 조건
    WHERE h < 23   
)

SELECT h.h AS HOUR, COUNT(o.ANIMAL_ID) AS COUNT
FROM hours h
LEFT JOIN ANIMAL_OUTS o
ON h.h = HOUR(o.DATETIME)
GROUP BY h.h
ORDER BY h.h




-- 2. 노가다
# FROM (
#   SELECT 0 h
#     UNION ALL SELECT 1 
#     UNION ALL SELECT 2 
#     UNION ALL SELECT 3 
#     UNION ALL SELECT 4 
#     UNION ALL SELECT 5 
#     UNION ALL SELECT 6 
#     UNION ALL SELECT 7 
#     UNION ALL SELECT 8 
#     UNION ALL SELECT 9 
#     UNION ALL SELECT 10 
#     UNION ALL SELECT 11 
#     UNION ALL SELECT 12 
#     UNION ALL SELECT 13 
#     UNION ALL SELECT 14 
#     UNION ALL SELECT 15 
#     UNION ALL SELECT 16 
#     UNION ALL SELECT 17 
#     UNION ALL SELECT 18 
#     UNION ALL SELECT 19 
#     UNION ALL SELECT 20 
#     UNION ALL SELECT 21 
#     UNION ALL SELECT 22 
#     UNION ALL SELECT 23
# ) h

-- 3. dual