-- hours 테이블 만드는 방법

-- 1. 재귀
WITH RECURSIVE hours AS (
    -- 초기값
    SELECT 0 AS hr
    -- 
    UNION ALL
    -- 재귀 부분
    SELECT hr + 1 
    FROM hours
    -- 기저 조건
    WHERE hr < 23   
)

SELECT h.hr AS HOUR, COUNT(o.ANIMAL_ID) AS COUNT
FROM hours h
LEFT JOIN ANIMAL_OUTS o
ON h.hr = HOUR(o.DATETIME)
GROUP BY h.hr
ORDER BY h.hr



-- 2. 노가다
# SELECT h.hr AS HOUR,
#        COUNT(o.ANIMAL_ID) AS COUNT
# FROM (
#   SELECT 0 hr
#     UNION ALL SELECT 1 
#     UNION ALL SELECT 2 
#     UNION ALL SELECT 3 
#     UNION ALL SELECT 4 
#     UNION ALL SELECT 5 
#     UNION ALL SELECT 6 
#     UNION ALL SELECT 7 
#     UNION ALL SELECT 8 
#     UNION ALL SELECT 9 
#     UNION ALL SELECT 10 
#     UNION ALL SELECT 11 
#     UNION ALL SELECT 12 
#     UNION ALL SELECT 13 
#     UNION ALL SELECT 14 
#     UNION ALL SELECT 15 
#     UNION ALL SELECT 16 
#     UNION ALL SELECT 17 
#     UNION ALL SELECT 18 
#     UNION ALL SELECT 19 
#     UNION ALL SELECT 20 
#     UNION ALL SELECT 21 
#     UNION ALL SELECT 22 
#     UNION ALL SELECT 23
# ) h
# LEFT JOIN ANIMAL_OUTS o
#   ON HOUR(o.DATETIME) = h.hr
# GROUP BY h.hr
# ORDER BY h.hr;
