SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d
JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) sc
ON (d.SKILL_CODE & sc.CODE) > 0
ORDER BY 1;
