SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC LIMIT 1
) c
JOIN MEMBER_PROFILE p ON c.MEMBER_ID = p.MEMBER_ID
JOIN REST_REVIEW r ON p.MEMBER_ID = r.MEMBER_ID
ORDER BY 3 ASC, 2 ASC; 