# SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
# FROM (
#     SELECT MEMBER_ID, COUNT(REVIEW_ID) AS CNT
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY 2 DESC LIMIT 1
# ) c
# JOIN MEMBER_PROFILE p ON c.MEMBER_ID = p.MEMBER_ID
# JOIN REST_REVIEW r ON p.MEMBER_ID = r.MEMBER_ID
# ORDER BY 3 ASC, 2 ASC;



# 복습1
WITH REVIEW_COUNT_TBL AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), MAX_TBL AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT_TBL
    WHERE REVIEW_COUNT = (
        SELECT MAX(REVIEW_COUNT)
        FROM REVIEW_COUNT_TBL
    )
)


SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MAX_TBL m ON r.MEMBER_ID = m.MEMBER_ID
JOIN MEMBER_PROFILE p ON p.MEMBER_ID = r.MEMBER_ID
ORDER BY 3 ASC, 2 ASC;


