SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n
ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.LENGTH = ( 
    SELECT MAX(LENGTH)
    FROM FISH_INFO i2
    WHERE i.FISH_TYPE = i2.FISH_TYPE
)
# group by가 아니라 직접 max length 구해서 찾음
ORDER BY ID

# SELECT i.ID, n.FISH_NAME, i.LENGTH
# FROM FISH_INFO i
# jOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
# WHERE (n.FISH_TYPE, i.LENGTH) 
#     IN (
#         SELECT FISH_TYPE, MAX(LENGTH)
#         FROM FISH_INFO
#         GROUP BY FISH_TYPE)
# order by i.id;