-- 코드를 작성해주세요
# 1) WITH TBL AS 사용 방법

# WITH SUM_TBL AS (
#     SELECT SUM(SCORE) AS SCORE, EMP_NO 
#     FROM HR_GRADE
#     WHERE YEAR = 2022
#     GROUP BY EMP_NO
# ), MAX_TBL AS (
#     SELECT MAX(SCORE) AS MAX_SCORE
#     FROM SUM_TBL
# )

# SELECT s.SCORE, s.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
# FROM HR_EMPLOYEES e
# JOIN SUM_TBL s ON e.EMP_NO = s.EMP_NO
# JOIN MAX_TBL m ON s.SCORE = m.MAX_SCORE # INNER JOIN


# 2) 내부 쿼리 사용 방법
SELECT g.SUM_SCORE AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) g
ON e.EMP_NO = g.EMP_NO
WHERE g.SUM_SCORE = (
    SELECT MAX(SUM_SCORE)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) T
)