SELECT b.CATEGORY, SUM(s.SALES) AS TOTAL_SALES
FROM BOOK_SALES s
JOIN BOOK b
ON s.BOOK_ID = b.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY CATEGORY ASC;