-- 코드를 입력하세요
SELECT a.CATEGORY, a.PRICE AS MAX_PRICE, a.PRODUCT_NAME
FROM FOOD_PRODUCT a
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
) b
ON a.CATEGORY = b.CATEGORY AND a.PRICE = b.MAX_PRICE
ORDER BY 2 DESC