-- 코드를 작성해주세요
WITH TBL AS (
    SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT, 
        AVG(LEN) AS AVG_LENGTH, MAX(LEN) AS MAX_LENGTH
    FROM (
        SELECT FISH_TYPE, COALESCE(LENGTH, 10) AS LEN
        FROM FISH_INFO
    ) f
    GROUP BY FISH_TYPE
)

SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM TBL t
WHERE t.AVG_LENGTH >= 33
ORDER BY 3 ASC




