WITH TBL AS (
SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'
), TBL2 AS (
SELECT 
CASE 
    WHEN d.SKILL_CODE & (SELECT CODE FROM TBL) > 0 
        AND d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
    WHEN d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
    WHEN d.SKILL_CODE & (SELECT CODE FROM TBL) > 0 THEN 'C'
    ELSE NULL
END AS GRADE
, d.ID, d.EMAIL
FROM DEVELOPERS d
ORDER BY GRADE, ID
)

SELECT * FROM TBL2 WHERE GRADE IS NOT NULL